/**
 * nav-data.js — AUTO-GENERATED by scripts/update-index.py
 * Generated: 2026-06-10
 * DO NOT edit by hand — run the script again to update.
 * To add custom descriptions/tags, edit the source index.html
 * using <meta name="description" content="..."> etc.
 */

const NAV_DATA = {

  meta: {
    title:       "Orbital Index",
    description: "Games, stories, and demos",
    generated:   "2026-06-10",
  },

  sections: {

    demos: {
      label: "Demos",
      items: [
        {
          title:    "Example Game Demo",
          path:     "demos/example-game/index.html",
          desc:     "A placeholder demo page. Replace with your actual game embed or write-up.",
          tag:      "playable",
          featured: true,
          updated:  "2026-06-10",
        },
      ],
    },

    stories: {
      label: "Stories",
      items: [
        {
          title:    "Example Story",
          path:     "stories/example-story/index.html",
          desc:     "A placeholder story entry. Replace with your actual narrative content.",
          tag:      "fiction",
          updated:  "2026-06-10",
        },
      ],
    },

  },

};
