/**
 * nav-data.js — AUTO-GENERATED by scripts/update-index.py
 * Generated: 2026-06-12
 * Set title/desc/tag via <title> and <meta name=...> in each project's index.html
 */

const NAV_DATA = {

  meta: { title: "Orbital Index", generated: "2026-06-12" },

  sections: {

    demos: {
      label: "Demos",
      items: [
        {
          title:   "Iron & Powder",
          path:    "demos/Iron-and-powder/index.html",
          updated: "2026-06-12",
        },
        {
          title:   "voxel terrain",
          path:    "demos/Voxel-world/index.html",
          updated: "2026-06-12",
        },
        {
          title:   "Example Game Demo",
          path:    "demos/example-game/index.html",
          desc:    "A placeholder demo page. Replace with your actual game embed or write-up.",
          tag:     "playable",
          featured: true,
          updated: "2026-06-12",
        },
      ],
    },

    stories: {
      label: "Stories",
      items: [
        {
          title:   "Example Story",
          path:    "stories/example-story/index.html",
          desc:    "A placeholder story entry. Replace with your actual narrative content.",
          tag:     "fiction",
          updated: "2026-06-12",
        },
      ],
    },

  },

};
