#!/usr/bin/env python3
import re, json, argparse
from datetime import datetime, timezone
from pathlib import Path

KNOWN_SECTIONS = {
    "demos":        "Demos",
    "stories":      "Stories",
    "explanations": "Explanations",
    "experiments":  "Experiments",
    "devlogs":      "Devlogs",
}

SKIP_DIRS = {
    ".git", ".github", "scripts", "node_modules",
    "__pycache__", ".vscode", ".idea", "assets", "css", "js",
}

def read_meta(html_path):
    try:
        text = html_path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return {}
    meta = {}
    m = re.search(r"<title[^>]*>(.*?)</title>", text, re.IGNORECASE | re.DOTALL)
    if m:
        meta["title"] = re.sub(r"\s+", " ", m.group(1)).strip()
    for key in ("description", "tag", "featured"):
        pattern = r'<meta\s+name=["\']' + key + r'["\']\s+content=["\'](.*?)["\']'
        m = re.search(pattern, text, re.IGNORECASE)
        if m:
            meta[key] = m.group(1).strip()
    if "featured" in meta:
        meta["featured"] = meta["featured"].lower() == "true"
    return meta

def folder_to_title(name):
    return name.replace("-", " ").replace("_", " ").title()

def get_mtime(path):
    return datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc).strftime("%Y-%m-%d")

def scan(root):
    sections = {}
    for section_dir in sorted(root.iterdir()):
        if not section_dir.is_dir():
            continue
        if section_dir.name.startswith(".") or section_dir.name in SKIP_DIRS:
            continue

        section_key   = section_dir.name.lower()
        section_label = KNOWN_SECTIONS.get(section_key, folder_to_title(section_dir.name))

        items = []
        for html in sorted(section_dir.rglob("index.html")):
            project_dir = html.parent
            if project_dir == section_dir:
                continue
            rel_parts = project_dir.relative_to(section_dir).parts
            if any(p.startswith(".") or p in SKIP_DIRS for p in rel_parts):
                continue
            meta     = read_meta(html)
            rel_path = html.relative_to(root).as_posix()
            item = {
                "title":    meta.get("title") or folder_to_title(project_dir.name),
                "path":     rel_path,
                "desc":     meta.get("description", ""),
                "tag":      meta.get("tag", ""),
                "featured": meta.get("featured", False),
                "updated":  get_mtime(html),
            }
            if not item["tag"]:      del item["tag"]
            if not item["desc"]:     del item["desc"]
            if not item["featured"]: del item["featured"]
            items.append(item)

        if items:
            sections[section_key] = {"label": section_label, "items": items}

    return sections

def render_js(sections, generated):
    lines = [
        "/**",
        " * nav-data.js — AUTO-GENERATED by scripts/update-index.py",
        f" * Generated: {generated}",
        " * Set title/desc/tag via <title> and <meta name=...> in each project's index.html",
        " */",
        "",
        "const NAV_DATA = {",
        "",
        f'  meta: {{ title: "Orbital Index", generated: "{generated}" }},',
        "",
        "  sections: {",
        "",
    ]
    for key, section in sections.items():
        lines += [
            f"    {key}: {{",
            f'      label: "{section["label"]}",',
            "      items: [",
        ]
        for item in section["items"]:
            lines.append("        {")
            lines.append(f'          title:   {json.dumps(item["title"])},')
            lines.append(f'          path:    {json.dumps(item["path"])},')
            if "desc"     in item: lines.append(f'          desc:    {json.dumps(item["desc"])},')
            if "tag"      in item: lines.append(f'          tag:     {json.dumps(item["tag"])},')
            if item.get("featured"): lines.append( '          featured: true,')
            lines.append(f'          updated: {json.dumps(item["updated"])},')
            lines.append("        },")
        lines += ["      ],", "    },", ""]
    lines += ["  },", "", "};", ""]
    return "\n".join(lines)

def find_root():
    by_script = Path(__file__).resolve().parent.parent
    if (by_script / "index.html").exists() and (by_script / "nav-data.js").exists():
        return by_script
    cwd = Path.cwd()
    if (cwd / "index.html").exists() and (cwd / "nav-data.js").exists():
        return cwd
    print("[orbital] ERROR: Can't find site root (needs index.html + nav-data.js).")
    print(f"  Tried: {by_script}")
    print(f"  Tried: {cwd}")
    raise SystemExit(1)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--root", type=Path, default=None)
    args = parser.parse_args()

    root = args.root.resolve() if args.root else find_root()
    print(f"[orbital] Scanning: {root}")

    sections = scan(root)
    total = sum(len(s["items"]) for s in sections.values())
    print(f"[orbital] Found {total} projects across {len(sections)} sections")
    for key, sec in sections.items():
        for item in sec["items"]:
            print(f"  {key}  →  {item['path']}")

    generated = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    output    = render_js(sections, generated)

    if args.dry_run:
        print("\n" + output)
        return

    out = root / "nav-data.js"
    out.write_text(output, encoding="utf-8")
    print(f"[orbital] Written → {out}")

if __name__ == "__main__":
    main()
